### ISSUE TITLE
Consider matching Python's default special handling for '.' in pathlib match functions

### ISSUE THREAD

**Issue by facelessuser** [facelessuser/wcmatch#92]
In our docs, we document the differences in our handling of matches and Python's default method of handling matches in a pathlib object: https://facelessuser.github.io/wcmatch/pathlib/#differences.

There are some very real differences, but most of them minor. They involve things like whether features are enabled by default or you have to enable them via flags. But one very real difference is the way Python handles `.` in pathlib match functions.

Python's default pathlib match function strips out `.` directories in all patterns and in all file paths. In file file paths, `.` is kind of redundant, so it makes sense that they get normalized and removed:

```py
>>> pathlib.Path('./docs/./src/././markdown')
WindowsPath('docs/src/markdown')
>>> pathlib.Path('./docs/./src/././markdown').match('././docs/././src/./markdown')
True
```

At first glance, one would think that there is logic to handle relative paths, but this is incorrect:

```py
>>> pathlib.Path('./docs/./src/././markdown').match('docs/src/../src/markdown')
False
```

How exactly it is done is irrelevant, but essentially, it is as if all `.` are either stripped or simply ignored.  But as noted above, relativity isn't truly handled, `.` is just simply ignored in one form or another, even if it makes no sense:

```py
>>> pathlib.Path('docs/src/markdown/index.md').match('docs/src/markdown/index.md/.')
True
```

I can understand why they do things like they do. It's more a convenience feature to allow patterns that start with `./` so that the user doesn't have to think about it. But, pathlib doesn't retain any real syntax to denote folders, so glob patterns like `*/folder/` won't match paths that are just folders because trailing `/` get normalized out of paths. For the same reason, patterns like `*/file/.` will match a file path even though it should be looking for a directory.

In short, the methodology behind what they are doing is kind of a naive approach. On the one hand I guess it makes sense that they normalize the pattern the same way they normalize the path, but it gives very surprising results. Especially compared to how our `globmatch` works out the box.

Our `globmatch` function is meant to match what `glob` globs. We outline in our own docs that Bash's glob returns files in a different way when `.` is included vs not included; therefore, it stands to reason that globmatch would match a path differently depending on whether `.` was included in the path or not.

The question is, whould we normalize glob patterns to strip out `.` or even `/` to match pathlib's path normalization?

- As far as `/` is concerned, I'd like to not allow this to be stripped out. This allows me to use a `Path` object with the REALPATH flag (which forces a touch to the file system) and request it to only find folders by giving it a pattern with a trailing `/`. This is useful.

- As far as `.` is concerned, I am torn. We could add an internal flag that tracks for a literal directory of `.` and strip them out, or at the very least allow them to be optional. It's a little tricky as there are features that make this a little more complex, and you have to scan for them in extended patterns such as `@(.)/path` etc., but it could be done.

The argument against doing any of this is simply that since a pathlib object strips out `.`, as a user, you probably shouldn't be using `.` in your glob patterns. If you are simply trying to account for a user's external input of `.`, and you want it to still match, then it may be beneficial.

Currently, my initial thought is to not bother with this, but I want to open the issue to allow discussion if others feel different.

**Comment by facelessuser** [comment]
Another bonkers case in the Python standard pathlib related to `.`

Here in Python's default pathlib, if you only provide a dot for a path, it will not strip the dot for a path as it needs to represent the current directory with something. A matter of fact, if you give it an empty string, it will force it to have a `.` as the path. Anyways, when you use a dot as the pattern to match that path, it strips the `.` in the pattern making the pattern an empty string. Now we have a path that is impossible to match:

```py
>>> import pathlib
>>> str(pathlib.Path('.'))
'.'
>>> pathlib.Path('.').match('.')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\WesternDigital_Tools\Python36\lib\pathlib.py", line 939, in match
    raise ValueError("empty pattern")
ValueError: empty pattern
```

In our implementation, we have no issue:

```py
>>> from wcmatch import pathlib
>>> pathlib.Path('.').match('.')
True
```

Yet another reason to not emulate like they do.

**Comment by facelessuser** [comment]
Created an issue on Python to track this odd behavior: https://bugs.python.org/issue39532.

If they were to fix this bug, it would allow us to re-evaluate potentially emulating this behavior if desired (probably with a flag).

@gir-bot remove S: triage
@gir-bot add T: feature, S: needs-decision, P: maybe

**Comment by facelessuser** [comment]
I think we've approached this as far as we are going to with recent features such as having glob not scan `.` and `..` by default etc.
